title: Marcos Crespo
logo: /assets/000044edit.JPG
description: Hola! Soy Marcos y aquí podrás encontrar todo lo que hago en Internet. Hablo de Ciencia de Datos y sobre música, mucha música. Escríbeme para cualquier pregunta o contacto!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
